server:
  port: 8082

spring:
  application:
    name: wallet-service
  threads:
    virtual:
      enabled: ${APP_VIRTUAL_THREADS_ENABLED:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/walletdb}
    username: ${SPRING_DATASOURCE_USERNAME:wallet}
    password: ${SPRING_DATASOURCE_PASSWORD:wallet}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

clients:
  user:
    base-url: http://localhost:8081

resilience4j:
  circuitbreaker:
    instances:
      userLookup:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      userLookup:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      service: ${spring.application.name}
